name = "substracker"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "substracker"

[env.staging]
name = "substracker-staging"

# KV 命名空间配置
[[kv_namespaces]]
binding = "SUBSCRIPTIONS_KV"
preview_id = "043feaa2eb8e4d02aa84ba1ee5f366bc"
id = "043feaa2eb8e4d02aa84ba1ee5f366bc"

# 定时任务配置 - 每天早上8点检查
[triggers]
crons = ["0 8 * * *"]

# 环境变量（可选，也可以在 Cloudflare Dashboard 中设置）
[vars]
ENVIRONMENT = "production"
